import type { WebsiteFunnelOverview } from "@/aggregation/services/website-funnel-types";

export function createWebsiteFunnelOverview(): WebsiteFunnelOverview {
  return {
    source: {
      state: "ready",
      candidateCount: 1,
      displayName: "MoonArq Website",
      status: "healthy",
    },
    dataState: "ready",
    range: {
      key: "30d",
      label: "Last 30 days",
      startDate: "2026-06-30",
      endDate: "2026-07-29",
      startAt: "2026-06-30T07:00:00.000Z",
      endExclusive: "2026-07-30T07:00:00.000Z",
      timeZone: "America/Los_Angeles",
      partialDay: true,
    },
    comparison: {
      mode: "previous",
      available: true,
      reason: null,
      startAt: "2026-05-31T07:00:00.000Z",
      endExclusive: "2026-06-30T07:00:00.000Z",
    },
    coverage: {
      firstOccurredAt: "2026-07-01T16:00:00.000Z",
      latestReceivedAt: "2026-07-29T18:00:00.000Z",
      startsDuringSelection: true,
    },
    filters: {
      segment: "all",
      device: "all",
      utmSource: "",
      utmMedium: "",
      utmCampaign: "",
      landingPath: "",
      referrerHost: "",
    },
    filterOptions: {
      devices: ["desktop", "mobile", "unknown"],
      utmSources: ["newsletter"],
      utmMediums: ["email"],
      utmCampaigns: ["summer"],
      landingPaths: ["/collections/new"],
      referrerHosts: ["example.test"],
    },
    acceptedEvents: 440,
    uniqueVisitors: 96,
    unfilteredEvents: 440,
    stages: [
      {
        key: "visit",
        label: "Website visits",
        description: "Sessions with an accepted page view.",
        measured: true,
        sessions: 120,
        events: 210,
        percentOfStart: 100,
        fromPrevious: null,
        dropOff: 60,
        previousSessions: 100,
        deltaPercent: 20,
      },
      {
        key: "product_intent",
        label: "Product intent",
        description: "Sessions with a collection, product, or builder intent event.",
        measured: true,
        sessions: 60,
        events: 82,
        percentOfStart: 50,
        fromPrevious: 50,
        dropOff: 36,
        previousSessions: 50,
        deltaPercent: 20,
      },
      {
        key: "add_to_cart",
        label: "Added to cart",
        description: "Sessions with a sequenced add-to-cart event.",
        measured: true,
        sessions: 24,
        events: 29,
        percentOfStart: 20,
        fromPrevious: 40,
        dropOff: 12,
        previousSessions: 20,
        deltaPercent: 20,
      },
      {
        key: "begin_checkout",
        label: "Checkout started",
        description: "Sessions with a sequenced checkout-start event.",
        measured: true,
        sessions: 12,
        events: 14,
        percentOfStart: 10,
        fromPrevious: 50,
        dropOff: null,
        previousSessions: 10,
        deltaPercent: 20,
      },
    ],
    trend: [
      {
        date: "2026-07-28",
        comparisonDate: "2026-06-28",
        current: {
          sessions: 12,
          product_intent: 6,
          add_to_cart: 3,
          checkout: 2,
          visit_to_checkout_rate: 16.7,
        },
        previous: {
          sessions: 10,
          product_intent: 5,
          add_to_cart: 2,
          checkout: 1,
          visit_to_checkout_rate: 10,
        },
      },
      {
        date: "2026-07-29",
        comparisonDate: "2026-06-29",
        current: {
          sessions: 8,
          product_intent: 4,
          add_to_cart: 1,
          checkout: 0,
          visit_to_checkout_rate: 0,
        },
        previous: null,
      },
    ],
    readyMade: {
      stages: [
        { label: "Ready-made visits", sessions: 80, events: 120, fromPrevious: null },
        { label: "Product views", sessions: 48, events: 65, fromPrevious: 60 },
        { label: "Added to cart", sessions: 20, events: 24, fromPrevious: 41.7 },
        { label: "Checkout started", sessions: 10, events: 12, fromPrevious: 50 },
      ],
    },
    builder: {
      starts: { label: "Build starts", sessions: 18, events: 22, fromPrevious: null },
      completions: { label: "Build completions", sessions: 9, events: 10, fromPrevious: 50 },
      saves: { label: "Designs saved", sessions: 5, events: 6, fromPrevious: 27.8 },
      completionRate: 50,
      saveRate: 27.8,
    },
    emailSignup: {
      sessions: 7,
      visitors: 6,
      events: 8,
    },
    collections: {
      rows: [
        {
          key: "unknown-collection",
          collectionName: "",
          collectionViewSessions: 4,
          productViewSessions: 1,
          progressionRate: 25,
          state: "unknown",
        },
      ],
      page: 1,
      pageSize: 10,
      totalRows: 1,
      hasPreviousPage: false,
      hasNextPage: false,
    },
    products: {
      rows: [
        {
          key: "unknown-product",
          itemId: null,
          itemName: "",
          itemCategory: "",
          productViewSessions: 3,
          addToCartSessions: 2,
          viewToCartRate: null,
          identityState: "unknown",
        },
        {
          key: "view-only-product",
          itemId: null,
          itemName: "Example necklace",
          itemCategory: "Necklaces",
          productViewSessions: 6,
          addToCartSessions: 0,
          viewToCartRate: null,
          identityState: "view_only",
        },
      ],
      page: 2,
      pageSize: 2,
      totalRows: 6,
      hasPreviousPage: true,
      hasNextPage: true,
    },
    acquisition: {
      rows: [
        {
          key: "newsletter-email",
          utmSource: "newsletter",
          utmMedium: "email",
          utmCampaign: "summer",
          landingPath: "/collections/new",
          referrerHost: "example.test",
          sessions: 20,
          productIntentSessions: 12,
          checkoutSessions: 3,
          visitToCheckoutRate: 15,
        },
      ],
      page: 1,
      pageSize: 10,
      totalRows: 1,
      hasPreviousPage: false,
      hasNextPage: false,
    },
    devices: [
      {
        device: "desktop",
        sessions: 70,
        productIntentSessions: 36,
        checkoutSessions: 8,
        visitToCheckoutRate: 11.4,
      },
      {
        device: "unknown",
        sessions: 2,
        productIntentSessions: 0,
        checkoutSessions: 0,
        visitToCheckoutRate: 0,
      },
    ],
    quality: {
      duplicateDeliveriesRemoved: 2,
      equalTimeIntentSessions: 1,
      equalTimeCartSessions: 0,
      equalTimeCheckoutSessions: 0,
      unsequencedIntentSessions: 1,
      unsequencedCartSessions: 2,
      unsequencedCheckoutSessions: 1,
      unknownEvents: [{ eventName: "unmapped_event", events: 2 }],
      unknownEventTotalRows: 1,
      invalidPropertyEvents: [{ eventName: "view_item", events: 1 }],
    },
    reconciliation: {
      state: "matched",
      rawPageViews: 210,
      dailyPageViews: 210,
      rawCustomEvents: 230,
      dailyCustomEvents: 230,
      note: "Raw first-party counts match the authoritative daily aggregates.",
    },
    lowVolume: false,
  };
}
