import type { MetricDefinition, SourceTypeKey } from "@/storage/db/schema";

const now = "2026-04-22T00:00:00.000Z";

function metric(
  key: string,
  display_name: string,
  description: string,
  source_type_key: SourceTypeKey | null,
  category: string,
  unit = "count",
  higher_is_better = true,
): MetricDefinition {
  return {
    key,
    display_name,
    description,
    source_type_key,
    category,
    unit,
    higher_is_better,
    created_at: now,
    updated_at: now,
  };
}

export const metricDefinitions: MetricDefinition[] = [
  metric("page_views", "Page views", "Authoritative first-party page_view events, grouped by occurred_at reporting day.", "website", "Website"),
  metric("unique_visitors", "Unique visitors", "Distinct first-party anonymous_id values per occurred_at reporting day.", "website", "Website"),
  metric("sessions", "Sessions", "Distinct first-party session_id values per occurred_at reporting day.", "website", "Website"),
  metric("custom_events", "Custom events", "Authoritative non-page_view events sent to /api/track, deduplicated by source and event ID.", "website", "Website"),
  metric("events_by_path", "Events by path", "Authoritative first-party events grouped by path and occurred_at reporting day.", "website", "Website"),
  metric("events_by_referrer", "Events by referrer", "Authoritative first-party events grouped by referrer and occurred_at reporting day.", "website", "Website"),
  metric("signups", "Signups", "New user signups from public profiles or Supabase Auth admin mode.", "supabase", "Users"),
  metric("users_total", "Total users", "Total known users from public profiles or server-side admin fallback.", "supabase", "Users"),
  metric("confirmed_users", "Confirmed users", "Users with confirmed email or equivalent profile state when available.", "supabase", "Users"),
  metric("signups_by_provider", "Signups by provider", "Signup count split by auth provider when available.", "supabase", "Users"),
  metric("deployment_count", "Deployments", "Future Vercel project deployment count.", "vercel_project", "Deployments"),
  metric("latest_deployment_status", "Deployment status", "Future Vercel latest deployment status.", "vercel_project", "Deployments"),
  metric("orders", "Orders", "Non-test Shopify orders grouped by the store-local order creation date.", "shopify", "Commerce"),
  metric("gross_sales", "Gross sales", "Shopify order subtotal plus pre-return discounts, excluding shipping and separately added taxes when prices are tax-exclusive.", "shopify", "Commerce", "currency"),
  metric("current_total", "Current total", "Shopify order total after returns, refunds, edits, and cancellations, grouped by store-local order creation date.", "shopify", "Commerce", "currency"),
  metric("net_payment", "Net payment", "Amount received for Shopify orders minus refunded amounts, grouped by store-local order creation date.", "shopify", "Commerce", "currency"),
  metric("refunds", "Refunds", "Total refunded amount attached to Shopify orders, grouped by store-local order creation date rather than refund event date.", "shopify", "Commerce", "currency", false),
  metric("top_products", "Ordered product units", "Non-test Shopify line-item quantity grouped by order, line item, product name, and store-local order creation date.", "shopify", "Commerce", "units"),
  metric("video_views", "Video views", "Legacy TikTok video views metric retained for compatibility.", "tiktok", "Content"),
  metric("likes", "Likes", "Legacy TikTok likes metric retained for compatibility.", "tiktok", "Content"),
  metric("comments", "Comments", "Legacy TikTok comments metric retained for compatibility.", "tiktok", "Content"),
  metric("shares", "Shares", "Legacy TikTok shares metric retained for compatibility.", "tiktok", "Content"),
  metric("tiktok_video_views", "TikTok video views", "Current cumulative views summed across videos returned by the latest TikTok video.list snapshot; do not sum snapshots across dates.", "tiktok", "Content"),
  metric("tiktok_likes", "TikTok video likes", "Current cumulative likes summed across videos returned by the latest TikTok video.list snapshot; distinct from profile likes.", "tiktok", "Content"),
  metric("tiktok_comments", "TikTok video comments", "Current cumulative comments summed across videos returned by the latest TikTok video.list snapshot.", "tiktok", "Content"),
  metric("tiktok_shares", "TikTok video shares", "Current cumulative shares summed across videos returned by the latest TikTok video.list snapshot.", "tiktok", "Content"),
  metric("tiktok_engagement_rate", "TikTok engagement rate", "Latest snapshot's cumulative likes, comments, and shares divided by cumulative video views.", "tiktok", "Content", "percent"),
  metric("tiktok_followers", "TikTok followers", "Current cumulative follower count from TikTok user.info.stats when granted.", "tiktok", "Content"),
  metric("tiktok_video_count", "TikTok video count", "Current public video count from TikTok user.info.stats when granted.", "tiktok", "Content"),
  metric("tiktok_profile_likes", "TikTok profile likes", "Current cumulative account likes_count from TikTok user.info.stats; may differ from the sum of returned public-video likes.", "tiktok", "Content"),
  metric("engagement_rate", "Engagement rate", "Engagement divided by reach, impressions, or views.", null, "Content", "percent"),
  metric("reach", "Reach", "Future Instagram reach.", "instagram", "Content"),
  metric("impressions", "Impressions", "Future Instagram impressions.", "instagram", "Content"),
  metric("followers", "Followers", "Future Instagram follower count.", "instagram", "Content"),
  metric("profile_views", "Profile views", "Future Instagram profile views.", "instagram", "Content"),
  metric("media_likes", "Media likes", "Future Instagram media likes.", "instagram", "Content"),
  metric("media_comments", "Media comments", "Future Instagram media comments.", "instagram", "Content"),
  metric("instagram_followers", "Instagram followers", "Followers for the connected Instagram account.", "instagram", "Content"),
  metric("instagram_media_count", "Instagram media count", "Total media count for the connected Instagram account.", "instagram", "Content"),
  metric("instagram_media_reach", "Instagram media reach", "Reach summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_media_likes", "Instagram media likes", "Likes summed from fetched Instagram media.", "instagram", "Content"),
  metric("instagram_media_comments", "Instagram media comments", "Comments summed from fetched Instagram media.", "instagram", "Content"),
  metric("instagram_media_saved", "Instagram media saved", "Saved count summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_media_total_interactions", "Instagram total interactions", "Total interactions summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_engagement_rate", "Instagram engagement rate", "Total interactions divided by media reach when available.", "instagram", "Content", "percent"),
  metric("meta_ads_spend", "Meta Ads spend", "Amount spent for the reporting day in the Meta ad account currency.", "meta_ads", "Paid media", "currency", false),
  metric("meta_ads_impressions", "Meta Ads impressions", "Paid ad impressions reported by Meta Ads Insights.", "meta_ads", "Paid media"),
  metric("meta_ads_reach", "Meta Ads ad-day reach", "Estimated reach reported for each ad/day row. Summing rows is an ad-day reach total, not unique period reach.", "meta_ads", "Paid media"),
  metric("meta_ads_frequency", "Meta Ads frequency", "Average paid impressions per reached account for the reporting day.", "meta_ads", "Paid media", "ratio", false),
  metric("meta_ads_clicks", "Meta Ads clicks", "All clicks reported by Meta Ads Insights.", "meta_ads", "Paid media"),
  metric("meta_ads_outbound_clicks", "Meta Ads outbound clicks", "Clicks that sent people away from Meta-owned surfaces.", "meta_ads", "Paid media"),
  metric("meta_ads_inline_link_clicks", "Meta Ads link clicks", "Inline link clicks reported by Meta Ads Insights.", "meta_ads", "Paid media"),
  metric("meta_ads_ctr", "Meta Ads CTR", "Click-through rate reported by Meta Ads Insights.", "meta_ads", "Paid media", "percent"),
  metric("meta_ads_cpc", "Meta Ads CPC", "Average cost per click reported by Meta Ads Insights.", "meta_ads", "Paid media", "currency", false),
  metric("meta_ads_cpm", "Meta Ads CPM", "Average cost per thousand impressions reported by Meta Ads Insights.", "meta_ads", "Paid media", "currency", false),
  metric("meta_ads_landing_page_views", "Meta landing page views", "Landing page view actions attributed by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_view_content", "Meta content views", "View-content actions attributed by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_add_to_cart", "Meta adds to cart", "Add-to-cart actions attributed by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_initiate_checkout", "Meta checkouts initiated", "Initiate-checkout actions attributed by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_purchases", "Meta purchases", "Purchase actions attributed by Meta under the selected attribution window.", "meta_ads", "Paid media"),
  metric("meta_ads_purchase_value", "Meta purchase value", "Purchase value attributed by Meta in the ad account currency.", "meta_ads", "Paid media", "currency"),
  metric("meta_ads_cost_per_purchase", "Meta cost per purchase", "Spend divided by Meta-attributed purchases when purchases are reported.", "meta_ads", "Paid media", "currency", false),
  metric("meta_ads_purchase_roas", "Meta purchase ROAS", "Purchase return on ad spend reported by Meta.", "meta_ads", "Paid media", "ratio"),
  metric("meta_ads_website_purchase_roas", "Meta website purchase ROAS", "Website purchase return on ad spend reported by Meta.", "meta_ads", "Paid media", "ratio"),
  metric("meta_ads_post_saves", "Meta post saves", "Post saves attributed to the ad by Meta, preferring the post_save action over its onsite conversion alias without double counting.", "meta_ads", "Paid media"),
  metric("meta_ads_post_reactions", "Meta post reactions", "Post reaction actions attributed to the ad by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_comments", "Meta ad comments", "Comment actions attributed to the ad by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_post_engagements", "Meta post engagements", "Post engagement actions attributed to the ad by Meta.", "meta_ads", "Paid media"),
  metric("meta_ads_video_p25", "Meta video 25% views", "Video-play actions reaching at least 25 percent.", "meta_ads", "Paid media"),
  metric("meta_ads_video_p50", "Meta video 50% views", "Video-play actions reaching at least 50 percent.", "meta_ads", "Paid media"),
  metric("meta_ads_video_p75", "Meta video 75% views", "Video-play actions reaching at least 75 percent.", "meta_ads", "Paid media"),
  metric("meta_ads_video_p95", "Meta video 95% views", "Video-play actions reaching at least 95 percent.", "meta_ads", "Paid media"),
  metric("meta_ads_video_p100", "Meta completed video views", "Video-play actions reaching 100 percent.", "meta_ads", "Paid media"),
  metric("meta_ads_video_thruplay", "Meta ThruPlays", "ThruPlay actions reported by Meta for video creative.", "meta_ads", "Paid media"),
  metric("shopify_attributed_orders", "Shopify UTM-attributed orders", "Non-test Shopify orders whose ready customer journey exactly matches the stored UTM dimensions.", "shopify", "Attribution"),
  metric("shopify_attributed_gross_sales", "Shopify UTM-attributed gross sales", "Gross sales for non-test Shopify orders grouped by ready first- or last-visit UTM dimensions.", "shopify", "Attribution", "currency"),
  metric("shopify_attributed_discounts", "Shopify UTM-attributed discounts", "Discounts applied to non-test Shopify orders grouped by ready first- or last-visit UTM dimensions.", "shopify", "Attribution", "currency", false),
  metric("shopify_attributed_current_total", "Shopify UTM-attributed current total", "Current order total after returns, refunds, edits, and cancellations for non-test Shopify orders grouped by ready first- or last-visit UTM dimensions.", "shopify", "Attribution", "currency"),
  metric("shopify_attributed_refunds", "Shopify UTM-attributed refunds", "Refunded amount attached to non-test Shopify orders grouped by ready first- or last-visit UTM dimensions and the order creation date.", "shopify", "Attribution", "currency", false),
  metric("shopify_attributed_net_revenue", "Shopify UTM-attributed net revenue", "Net payment for non-test Shopify orders grouped by ready first- or last-visit UTM dimensions.", "shopify", "Attribution", "currency"),
  metric("etsy_orders", "Etsy orders", "Etsy receipts where money changed hands (paid and not canceled, or refunded), by the Pacific date the order was placed; refunded and canceled-and-refunded orders keep counting here, and their refunds count under Etsy refunds.", "etsy", "Commerce"),
  metric("etsy_sales", "Etsy sales", "Gross receipt subtotals (item prices times quantities, minus shop coupons; no shipping or tax) of the orders counted under Etsy orders, by the Pacific date the order was placed, in the shop's currency. Refunds are counted under Etsy refunds, not subtracted here.", "etsy", "Commerce", "currency"),
  metric("etsy_units_sold", "Etsy units sold", "Quantities on the transactions of the orders counted under Etsy orders, by the Pacific date the order was placed.", "etsy", "Commerce"),
  metric("etsy_refunds", "Etsy refunds", "Refund amounts Etsy reports on receipts, cancellations included, by the Pacific date each refund was issued, in the shop's currency.", "etsy", "Commerce", "currency", false),
  metric("etsy_active_listings", "Etsy active listings", "The shop's active listing count as Etsy reports it, recorded for each Pacific date the shop was synced.", "etsy", "Commerce"),
  metric("whatnot_sales", "Whatnot completed sales", "Item sale prices after seller coupons (Post Coupon Price, the amount Whatnot charges commission on) for Order Earnings rows of the imported Weekly Orders Report, giveaways excluded, by the Pacific date the order completed (about four hours after delivery, or at label creation with Early Payout).", "whatnot", "Commerce", "currency"),
  metric("whatnot_orders", "Whatnot completed orders", "Distinct Order IDs among Order Earnings rows of the imported Weekly Orders Report, giveaways excluded, by the Pacific date the order completed.", "whatnot", "Commerce"),
  metric("whatnot_items_sold", "Whatnot items sold", "Quantity Sold on Order Earnings rows of the imported Weekly Orders Report (one when blank), giveaways excluded, by the Pacific date the order completed.", "whatnot", "Commerce"),
  metric("whatnot_net_earnings", "Whatnot net earnings", "Signed Transaction Amount across every row of the imported Weekly Orders Report (sales after fees, refunds, tips, shipping charges, and the shipping paid for giveaways): what reached the Whatnot balance, by the Pacific date the transaction completed.", "whatnot", "Commerce", "currency"),
  metric("whatnot_fees", "Whatnot fees", "Commission, payment processing, and the taxes on both for Order Earnings rows of the imported Weekly Orders Report, by the Pacific date the order completed.", "whatnot", "Commerce", "currency", false),
  metric("whatnot_refunds", "Whatnot refunds", "Amounts returned to buyers on Order Refund rows of the imported Weekly Orders Report, by the Pacific date the refund completed.", "whatnot", "Commerce", "currency", false),
  metric("whatnot_tips", "Whatnot tips", "Tips received on Tips rows of the imported Weekly Orders Report, by the Pacific date the transaction completed.", "whatnot", "Commerce", "currency"),
  metric("whatnot_shipping_charges", "Whatnot shipping charges", "Additional shipping costs owed to Whatnot on Shipping Charge rows of the imported Weekly Orders Report, by the Pacific date the charge completed.", "whatnot", "Commerce", "currency", false),
  metric("whatnot_show_sales", "Whatnot completed sales by show", "Completed Whatnot sales (giveaways excluded) per Livestream ID and Pacific completion date, labelled with the day the show ran (its earliest order); sales outside a show are grouped as marketplace.", "whatnot", "Commerce", "currency"),
  metric("whatnot_show_orders", "Whatnot completed orders by show", "Distinct completed Whatnot orders per Livestream ID and Pacific completion date.", "whatnot", "Commerce"),
  metric("whatnot_show_items", "Whatnot items by show", "Whatnot items sold per Livestream ID and Pacific completion date.", "whatnot", "Commerce"),
  metric("active_sources", "Active sources", "Sources currently enabled and healthy enough to collect data.", null, "System"),
  metric("sync_errors", "Sync errors", "Sync runs ending in an error state.", null, "System", "count", false),
];
