import type { MetricDefinition, SourceTypeKey } from "@/storage/db/schema";

const now = "2026-04-22T00:00:00.000Z";

function metric(
  key: string,
  display_name: string,
  description: string,
  source_type_key: SourceTypeKey | null,
  category: string,
  unit = "count",
  higher_is_better = true,
): MetricDefinition {
  return {
    key,
    display_name,
    description,
    source_type_key,
    category,
    unit,
    higher_is_better,
    created_at: now,
    updated_at: now,
  };
}

export const metricDefinitions: MetricDefinition[] = [
  metric("page_views", "Page views", "Tracked website page view events.", "website", "Website"),
  metric("unique_visitors", "Unique visitors", "Distinct anonymous visitors observed by first-party tracking.", "website", "Website"),
  metric("sessions", "Sessions", "Distinct visitor sessions observed by first-party tracking.", "website", "Website"),
  metric("custom_events", "Custom events", "Named product or marketing events sent to /api/track.", "website", "Website"),
  metric("events_by_path", "Events by path", "Website events grouped by path.", "website", "Website"),
  metric("events_by_referrer", "Events by referrer", "Website events grouped by referrer.", "website", "Website"),
  metric("signups", "Signups", "New user signups from public profiles or Supabase Auth admin mode.", "supabase", "Users"),
  metric("users_total", "Total users", "Total known users from public profiles or server-side admin fallback.", "supabase", "Users"),
  metric("confirmed_users", "Confirmed users", "Users with confirmed email or equivalent profile state when available.", "supabase", "Users"),
  metric("signups_by_provider", "Signups by provider", "Signup count split by auth provider when available.", "supabase", "Users"),
  metric("deployment_count", "Deployments", "Future Vercel project deployment count.", "vercel_project", "Deployments"),
  metric("latest_deployment_status", "Deployment status", "Future Vercel latest deployment status.", "vercel_project", "Deployments"),
  metric("orders", "Orders", "Future Shopify order count.", "shopify", "Commerce"),
  metric("gross_sales", "Gross sales", "Future Shopify gross sales.", "shopify", "Commerce", "currency"),
  metric("current_total", "Current total", "Future Shopify current order total.", "shopify", "Commerce", "currency"),
  metric("net_payment", "Net payment", "Future Shopify net payment.", "shopify", "Commerce", "currency"),
  metric("refunds", "Refunds", "Future Shopify refund amount.", "shopify", "Commerce", "currency", false),
  metric("top_products", "Top products", "Future Shopify product ranking metric.", "shopify", "Commerce"),
  metric("video_views", "Video views", "Legacy TikTok video views metric retained for compatibility.", "tiktok", "Content"),
  metric("likes", "Likes", "Legacy TikTok likes metric retained for compatibility.", "tiktok", "Content"),
  metric("comments", "Comments", "Legacy TikTok comments metric retained for compatibility.", "tiktok", "Content"),
  metric("shares", "Shares", "Legacy TikTok shares metric retained for compatibility.", "tiktok", "Content"),
  metric("tiktok_video_views", "TikTok video views", "Views summed from fetched public TikTok videos.", "tiktok", "Content"),
  metric("tiktok_likes", "TikTok likes", "Likes summed from fetched public TikTok videos.", "tiktok", "Content"),
  metric("tiktok_comments", "TikTok comments", "Comments summed from fetched public TikTok videos.", "tiktok", "Content"),
  metric("tiktok_shares", "TikTok shares", "Shares summed from fetched public TikTok videos.", "tiktok", "Content"),
  metric("tiktok_engagement_rate", "TikTok engagement rate", "Likes, comments, and shares divided by views.", "tiktok", "Content", "percent"),
  metric("tiktok_followers", "TikTok followers", "Follower count from TikTok user.info.stats when granted.", "tiktok", "Content"),
  metric("tiktok_video_count", "TikTok video count", "Public video count from TikTok user.info.stats when granted.", "tiktok", "Content"),
  metric("tiktok_profile_likes", "TikTok profile likes", "Total likes count from TikTok user.info.stats when granted.", "tiktok", "Content"),
  metric("engagement_rate", "Engagement rate", "Engagement divided by reach, impressions, or views.", null, "Content", "percent"),
  metric("reach", "Reach", "Future Instagram reach.", "instagram", "Content"),
  metric("impressions", "Impressions", "Future Instagram impressions.", "instagram", "Content"),
  metric("followers", "Followers", "Future Instagram follower count.", "instagram", "Content"),
  metric("profile_views", "Profile views", "Future Instagram profile views.", "instagram", "Content"),
  metric("media_likes", "Media likes", "Future Instagram media likes.", "instagram", "Content"),
  metric("media_comments", "Media comments", "Future Instagram media comments.", "instagram", "Content"),
  metric("instagram_followers", "Instagram followers", "Followers for the connected Instagram account.", "instagram", "Content"),
  metric("instagram_media_count", "Instagram media count", "Total media count for the connected Instagram account.", "instagram", "Content"),
  metric("instagram_media_reach", "Instagram media reach", "Reach summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_media_likes", "Instagram media likes", "Likes summed from fetched Instagram media.", "instagram", "Content"),
  metric("instagram_media_comments", "Instagram media comments", "Comments summed from fetched Instagram media.", "instagram", "Content"),
  metric("instagram_media_saved", "Instagram media saved", "Saved count summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_media_total_interactions", "Instagram total interactions", "Total interactions summed from available Instagram media insights.", "instagram", "Content"),
  metric("instagram_engagement_rate", "Instagram engagement rate", "Total interactions divided by media reach when available.", "instagram", "Content", "percent"),
  metric("active_sources", "Active sources", "Sources currently enabled and healthy enough to collect data.", null, "System"),
  metric("sync_errors", "Sync errors", "Sync runs ending in an error state.", null, "System", "count", false),
];
